# Initialization for current mirror

In [1]:
import scqubits as qubit
import numpy as np

In [2]:
N = 2  # number of big capacitors; changing to N=3 increases runtime but yields multiple inequivalent minima
maximum_periodic_vector_length = 8
ECB = 0.2
ECJ = 5.0
ECg = 10.0
flux = 0.0
EJ = 10.0
EJlist = np.array([EJ for j in range(2*N)])
nglist = np.array([0.0 for j in range(2*N-1)])
num_exc = 2
param_dict = {"N":N, "ECB":ECB, "ECJ":ECJ, "ECg":ECg, "EJlist":EJlist, "nglist":nglist, "flux":flux,
              "maximum_periodic_vector_length":maximum_periodic_vector_length, "num_exc":num_exc, 
              "truncated_dim":6, "quiet":True}
CMV = qubit.CurrentMirrorVCHOS(**param_dict)  # vanilla tight binding
CMVS = qubit.CurrentMirrorVCHOSSqueezing(**param_dict)  # tight-binding using squeezing
param_dict.pop("num_exc")
param_dict["global_exc"] = 2
CMVG = qubit.CurrentMirrorVCHOSGlobal(**param_dict)  # tight-binding using a global cutoff
CMVGS = qubit.CurrentMirrorVCHOSGlobalSqueezing(**param_dict)  # tight-binding using squeezing and a global cutoff

# Eigensystem

In [3]:
evals, evecs = CMV.eigensys()
evals_squeezing, evecs_squeezing = CMVS.eigensys()
evals_global, evecs_global = CMVG.eigensys()
evals_global_squeezing, evecs_global_squeezing = CMVGS.eigensys()

In [4]:
evals, evals_squeezing, evals_global, evals_global_squeezing

(array([12.7581796 , 16.34967861, 16.34967861, 19.84874759, 19.85836551,
        19.93760869]),
 array([12.7581796 , 16.34967861, 16.34967861, 19.84874759, 19.85836551,
        19.93760869]),
 array([12.7617841 , 16.40987813, 16.40987813, 19.93325639, 19.94382264,
        20.01387534]),
 array([12.7617841 , 16.40987813, 16.40987813, 19.93325639, 19.94382264,
        20.01387534]))

# Harmonic length optimization

In [5]:
CMV.harmonic_length_optimization = 1
CMVS.harmonic_length_optimization = 1
CMVG.harmonic_length_optimization = 1
CMVGS.harmonic_length_optimization = 1

In [6]:
evals, evecs = CMV.eigensys()
evals_squeezing, evecs_squeezing = CMVS.eigensys()
evals_global, evecs_global = CMVG.eigensys()
evals_global_squeezing, evecs_global_squeezing = CMVGS.eigensys()

In [7]:
evals, evals_squeezing, evals_global, evals_global_squeezing

(array([12.75664088, 16.31747114, 16.31747114, 19.7692745 , 19.77712469,
        19.87182403]),
 array([12.75664088, 16.31747113, 16.31747114, 19.7692745 , 19.77712469,
        19.87182402]),
 array([12.75939247, 16.32222425, 16.32222425, 19.78559639, 19.78963232,
        19.88505341]),
 array([12.75939247, 16.32222425, 16.32222425, 19.78559639, 19.78963231,
        19.88505341]))

In [8]:
CMV.optimized_lengths, CMVS.optimized_lengths

(array([[1.04723435, 1.04723435, 1.04694553]]),
 array([[1.04723434, 1.04723438, 1.04694553]]))

# Optimize harmonic lengths in inequivalent minima (squeezing only)

In [9]:
CMVS.optimize_all_minima = 1
CMVGS.optimize_all_minima = 1

In [10]:
evals_squeezing, evecs_squeezing = CMVS.eigensys()
evals_global_squeezing, evecs_global_squeezing = CMVGS.eigensys()

In [11]:
evals_squeezing, evals_global_squeezing

(array([12.75664088, 16.31747113, 16.31747114, 19.7692745 , 19.77712469,
        19.87182402]),
 array([12.75939247, 16.32222425, 16.32222425, 19.78559639, 19.78963231,
        19.88505341]))

In [12]:
CMVS.optimized_lengths

array([[1.04723434, 1.04723438, 1.04694553]])